import { Link, useOutletContext } from "react-router-dom";

function Home() {

    return (
        <div className="main">
            <div className="main-prop">
                <h1>AI-powered language learning<br />for intermediate and advanced levels.</h1>
                <Link to="/courses/" className="explore-button">Explore Courses</Link>
            </div>
                
            <div className="hp-pillars">
                <div className="pillar">
                    <img src=""></img>
                    <h1>Read</h1>
                    <p>Gain access to hundreds of lessons covering interesting topics.</p></div>
                <div className="pillar">
                    <img src=""></img>
                    <h2>Write</h2>
                    <p>Practice writing in your target language.</p></div>
                <div className="pillar">
                    <img src=""></img>
                    <h1>Get feedback</h1>
                    <p>Get real-time feedback on your writing, generated by AI.</p></div>
            </div>
        </div>
    )
}

export default Home;