"""Added name column to User table

Revision ID: 02236a983139
Revises: a908df95e1ea
Create Date: 2024-02-21 10:47:10.908619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02236a983139'
down_revision = 'a908df95e1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
