"""added usertopic relationship

Revision ID: 38be2b446b39
Revises: da431b796c74
Create Date: 2024-02-26 10:44:34.372176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38be2b446b39'
down_revision = 'da431b796c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_users_topics_topic_id_topics')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_topics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_topics'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_topics')
    # ### end Alembic commands ###
