"""rmv usertopic

Revision ID: 74d30be57968
Revises: 38be2b446b39
Create Date: 2024-02-26 17:17:02.694599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d30be57968'
down_revision = '38be2b446b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_topics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_topics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('topic_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='fk_users_topics_topic_id_topics'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_topics_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_users_topics')
    )
    # ### end Alembic commands ###
