"""added topic

Revision ID: 8a70eda7ad9b
Revises: c605a97a357f
Create Date: 2024-02-26 10:19:55.104006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a70eda7ad9b'
down_revision = 'c605a97a357f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('topic_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    # ### end Alembic commands ###
