"""readd usertopic

Revision ID: 9f391a4ad639
Revises: 74d30be57968
Create Date: 2024-02-26 18:51:02.943119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f391a4ad639'
down_revision = '74d30be57968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_users_topics_topic_id_topics')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_topics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_topics'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_topics')
    # ### end Alembic commands ###
