"""added UserLessons"


Revision ID: c605a97a357f
Revises: e19330ab6818
Create Date: 2024-02-23 16:56:51.838289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c605a97a357f'
down_revision = 'e19330ab6818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_course_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_users_lessons_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['user_course_id'], ['users_courses.id'], name=op.f('fk_users_lessons_user_course_id_users_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_lessons'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_lessons')
    # ### end Alembic commands ###
