"""added questions, userquestions

Revision ID: d29dcf15fc7e
Revises: 9f391a4ad639
Create Date: 2024-02-28 12:33:51.072696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29dcf15fc7e'
down_revision = '9f391a4ad639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('prev_question', sa.Integer(), nullable=True),
    sa.Column('next_question', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_questions_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['next_question'], ['questions.id'], name=op.f('fk_questions_next_question_questions')),
    sa.ForeignKeyConstraint(['prev_question'], ['questions.id'], name=op.f('fk_questions_prev_question_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('users_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_input', sa.String(), nullable=True),
    sa.Column('ai_feedback', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_users_questions_question_id_questions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_questions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_questions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
