"""added topics relationships

Revision ID: da431b796c74
Revises: 8a70eda7ad9b
Create Date: 2024-02-26 10:26:25.965893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da431b796c74'
down_revision = '8a70eda7ad9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_topic_id_topics'), 'topics', ['topic_id'], ['id'])

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_lessons_topic_id_topics'), 'topics', ['topic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lessons_topic_id_topics'), type_='foreignkey')
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_topic_id_topics'), type_='foreignkey')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
