"""lessons as linked lists

Revision ID: e19330ab6818
Revises: 77d48a91c2b2
Create Date: 2024-02-23 13:26:30.601052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19330ab6818'
down_revision = '77d48a91c2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_lesson', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_lesson', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lesson_type', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_lessons_prev_lesson_lessons'), 'lessons', ['prev_lesson'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_lessons_next_lesson_lessons'), 'lessons', ['next_lesson'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lessons_next_lesson_lessons'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_lessons_prev_lesson_lessons'), type_='foreignkey')
        batch_op.drop_column('lesson_type')
        batch_op.drop_column('next_lesson')
        batch_op.drop_column('prev_lesson')

    # ### end Alembic commands ###
